"""Shared paths and frozen model constants for every stage of the pipeline."""

import os
from pathlib import Path

PROJECT_ROOT = Path(
    os.environ.get("TICKET_CLASSIFIER_PROJECT_ROOT", Path(__file__).resolve().parents[2])
).resolve()

TEXT_COLUMN = "Document"
LABEL_COLUMN = "Topic_group"
ID_COLUMN = "record_id"
RANDOM_SEED = 42

TFIDF_NGRAM_RANGE = (1, 1)
TFIDF_MIN_DF = 2
TFIDF_NORM = "l2"
TFIDF_SUBLINEAR_TF = True

LOGISTIC_REGRESSION_C = 1.0
LOGISTIC_REGRESSION_SOLVER = "lbfgs"
LOGISTIC_REGRESSION_MAX_ITER = 1_000

EXPECTED_TRAIN_ROWS = 38_109
EXPECTED_VALIDATION_ROWS = 9_528
EXPECTED_TRAIN_SHA256 = "62DA11CE58FA9EAF6C3AC04A77BE24FC0C66A97864829D68CA98FDBE6FDDF894"
EXPECTED_VALIDATION_SHA256 = "4EEA86B63A3E3D7186C6F52C3FFF41D6D8E266679D7B9496428E3E2971366DB0"

DEFAULT_TRAIN_PATH = PROJECT_ROOT / "data" / "splits" / "train.csv"
DEFAULT_VALIDATION_PATH = PROJECT_ROOT / "data" / "splits" / "validation.csv"
DEFAULT_DEVELOPMENT_ARTIFACT_DIR = PROJECT_ROOT / "outputs" / "development"
DEFAULT_DEVELOPMENT_MODEL_PATH = DEFAULT_DEVELOPMENT_ARTIFACT_DIR / "model.joblib"
DEFAULT_DEVELOPMENT_PREDICTIONS_PATH = (
    DEFAULT_DEVELOPMENT_ARTIFACT_DIR / "validation_predictions.csv"
)
LEGACY_E04_MODEL_PATH = (
    PROJECT_ROOT
    / "experiments"
    / "classification"
    / "e04_moderate_weights"
    / "outputs"
    / "model.joblib"
)
